# Generated by Django 5.0.14 on 2026-05-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='type',
            field=models.CharField(choices=[('system', 'System'), ('custom', 'Custom'), ('customer', 'Customer')], default='custom', max_length=20),
        ),
    ]
