# Generated by Django 5.0.14 on 2026-03-07 20:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_defectcode_anomalysnapshot_productionlog_scraplog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('HEARTBEAT_LOST', 'Heartbeat Lost'), ('HEARTBEAT_RESTORED', 'Heartbeat Restored'), ('STATUS_CHANGE', 'Status Change')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.machine')),
            ],
        ),
        migrations.CreateModel(
            name='TelemetryPacket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('spindle_speed', models.FloatField()),
                ('feed_rate', models.FloatField()),
                ('temperature', models.FloatField()),
                ('vibration', models.FloatField()),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telemetry_packets', to='core.workorderexecution')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_packets', to='core.machine')),
            ],
            options={
                'indexes': [models.Index(fields=['machine', 'timestamp'], name='core_teleme_machine_cb87db_idx')],
            },
        ),
    ]
