# Generated by Django 5.0.14 on 2026-05-16 08:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dataexportjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderexecution',
            name='status',
            field=models.CharField(choices=[('AWAITING_START', 'Awaiting Start'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed')], default='RUNNING', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('IDLE', 'Idle'), ('MAINTENANCE', 'Maintenance')], default='IDLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machines', models.ManyToManyField(blank=True, related_name='production_lines', to='core.machine')),
            ],
        ),
        migrations.AddField(
            model_name='workorder',
            name='production_line',
            field=models.ForeignKey(blank=True, help_text='Optional production line assignment for this work order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='core.productionline'),
        ),
    ]
