# Generated by Django 5.0.14 on 2026-05-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_workorderexecution_status_productionline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Customer-facing deadline for this work order.', null=True),
        ),
    ]
