# Generated by Django 5.0.14 on 2026-05-26 14:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_part_model_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('file_3d', models.FileField(help_text='Original 3D file (.stl, .obj)', upload_to='order_requests/original/')),
                ('file_glb', models.FileField(blank=True, help_text='Converted 3D file for web (.glb)', null=True, upload_to='order_requests/web/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='Customer who placed the request', on_delete=django.db.models.deletion.CASCADE, related_name='order_requests', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.OneToOneField(blank=True, help_text='The work order generated from this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_request', to='core.workorder')),
            ],
        ),
    ]
