# Generated by Django 5.0.14 on 2026-05-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_orderrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='file_3d',
            field=models.FileField(blank=True, help_text='Original 3D file (.stl, .obj)', null=True, upload_to='order_requests/original/'),
        ),
    ]
