# Generated by Django 5.0.14 on 2026-05-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_orderrequest_file_3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if the order is rejected', null=True),
        ),
    ]
