# Generated by Django 5.0.14 on 2026-05-27 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_orderrequest_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='title',
            field=models.CharField(blank=True, help_text='Title or name of the order', max_length=200, null=True),
        ),
    ]
