# Generated by Django 5.0.14 on 2026-05-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_orderrequest_status_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionline',
            name='machine_sequence',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of machine UUIDs for this line'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
