# Generated by Django 5.0.14 on 2026-06-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_productionline_machine_sequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderexecution',
            name='program_ends_at',
            field=models.DateTimeField(blank=True, help_text='Scheduled simulator program completion time. Persisted so running programs survive simulator/backend restarts.', null=True),
        ),
    ]
